site_name: Personal Message Bus
site_url: http://docs.pmb.io/
site_description: Project documentation for PMB.

theme: cosmo
copyright: Copyright &copy; 2014, <a href="https://twitter.com/ndj">Nate Jones</a>.
repo_url: https://github.com/justone/pmb

pages:
- ['index.md', 'Home']
- ['getting_started.md', 'Documentation', 'Getting Started']
