site_name: Personal Message Bus
site_url: http://docs.pmb.io/
site_description: Project documentation for PMB.

theme: cosmo
copyright: Copyright &copy; 2014, <a href="https://twitter.com/ndj">Nate Jones</a>.
repo_url: https://github.com/justone/pmb

pages:
- ['index.md', 'Home']
- ['getting_started.md', 'Documentation', 'Getting Started']
- ['configuration.md', 'Documentation', 'Configuration']
- ['messages.md', 'Documentation', 'Message Descriptions']
- ['core.md', 'Documentation', 'Core Functionality']
- ['concepts/introduction.md', 'Concepts', 'Introduction']
- ['concepts/fact_driven.md', 'Concepts', 'Fact Driven Development']
